version: '3.8'

# This docker compose gets postgres and rsshub up.
# Be careful with the db password as it is set open to the world rn

# .env format:
# RSSHUB_BASE="http://ip:1200/telegram/channel/{channel}"
# DB_USER=
# DB_PASSWORD=at least 16char long i would recommend
# DB_NAME=
# DATABASE_URL=postgresql+asyncpg://user:password@ip:5432/db_name

services:
  postgres:
    image: postgres:16-alpine
    container_name: summary_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  rsshub:
    image: diygod/rsshub:latest
    container_name: rsshub
    restart: always
    ports:
      - "${RSSHUB_PORT:-1200}:1200"
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=memory
      - MEMORY_MAX_HOST_SIZE=1024
      - TG_OPTIONS_TIMEOUT=15000


volumes:
  pg_data: