version: '3.8'
# Docker compose to start you own RSSHUB, minimal hardware requirements

services:
  rsshub:
    image: diygod/rsshub:latest
    ports:
      - "1200:1200"
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=memory
      - MEMORY_MAX_HOST_SIZE=1024
      - TG_OPTIONS_TIMEOUT=15000
    restart: always